<?php
namespace app\index\model;

use think\Model;


class Blog extends Model
{
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function get_list(){
        return $this->select()->toArray();
    }
}